# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
